version: '2'
services:
  database:
    image: $DATABASE_IMAGE
    ports:
      - 1521
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD= 
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_USER=sakai
      - MYSQL_PASSWORD=sakai
      - MYSQL_DATABASE=sakai
    command: --character-set-server=utf8
  sakai:
    image: $SAKAI_IMAGE
    ports:
      - 8080
    links:
      - database
    environment:
      - CATALINA_OPTS_EXTRA=-Dsakai.demo=true -Dsakai.security=/usr/local/tomcat-base/security-$DATABASE_TYPE
      - CATALINA_BASE=/usr/local/tomcat-base
    command: ["/usr/local/tomcat-base/bin/wait-before.sh", "$DATABASE_TYPE", "catalina.sh", "run"]      
