version: '2'
services:
  database:
    image: $DATABASE_IMAGE
    ports:
      - $DATABASE_PORT
    volumes_from:
      - sakai
    environment:
      - MYSQL_ROOT_PASSWORD= 
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_USER=sakai
      - MYSQL_PASSWORD=sakai
      - MYSQL_DATABASE=sakai
    command:
      - $DATABASE_KEY=$DATABASE_VALUE
  tomcat:
    image: tomcat:8.0.41-jre8
    ports:
      - 8080
    links:
      - database
    volumes_from:
      - sakai
    environment:
      - CATALINA_OPTS_EXTRA=-Dsakai.demo=true
      - CATALINA_BASE=/usr/local/tomcat-base
    command: ["/usr/local/tomcat-base/bin/wait-before.sh", "catalina.sh", "run"]      
  sakai:
    image: $SAKAI_IMAGE
    volumes:
      - base:/usr/local/tomcat-base
      - db:/docker-entrypoint-initdb.d
volumes:
  base:
    driver: local
  db:
    driver: local